security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                # Redirection gérée dans SecurityController selon le rôle
                default_target_path: app_account
                always_use_default_target_path: false
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } 
        - { path: ^/mon-compte, roles: ROLE_USER }