security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true 
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/webhook/stripe, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/murder-parties$, roles: PUBLIC_ACCESS }
        - { path: ^/api/game-sessions/join, roles: PUBLIC_ACCESS }
        - { path: ^/api/avatars, roles: PUBLIC_ACCESS }
        - { path: ^/api/game-sessions/.*/players, roles: PUBLIC_ACCESS }
        - { path: ^/api/murder-parties/.*/ownership, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/game-sessions/.*/epilogue, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN } 
        - { path: ^/mon-compte, roles: ROLE_USER }