<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260309133325 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bloc_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\' NOT NULL, game_player_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BBC1574B4034DD ON bloc_notes (game_player_id)');
        $this->addSql('ALTER TABLE bloc_notes ADD CONSTRAINT FK_5BBC1574B4034DD FOREIGN KEY (game_player_id) REFERENCES game_players (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_players ALTER id DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('ALTER TABLE bloc_notes DROP CONSTRAINT FK_5BBC1574B4034DD');
        $this->addSql('DROP TABLE bloc_notes');
        $this->addSql('ALTER TABLE game_players ALTER id SET DEFAULT \'gen_random_uuid()\'');
    }
}
