parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    avatar_mp_directory: '%kernel.project_dir%/public/uploads/avatar_mp'
    covers_directory: '%kernel.project_dir%/public/uploads/covers'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    mailer.default_transport:
        alias: mailer.transport.brevo

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\BrevoService:
        arguments:
            $brevoApiKey: '%env(BREVO_API_KEY)%'