parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    avatar_mp_directory: '%kernel.project_dir%/public/uploads/avatar_mp'
    covers_directory: '%kernel.project_dir%/public/uploads/covers'

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\Repository\StatRepository:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'

    App\:
        resource: '../src/'
        
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

